language: node_js
node_js:
- '8'
cache:
- node_modules
env:
  global:
<<<<<<< HEAD
  - secure: URTZgBumQl9SO2OQi8uKz46f39d6VJ1QL1Gkp3L6crCBb8h8pSkR/+ASdEFyXJ+veA7J5df3PVgLwOVRYNmv6Imhc6oVPQYam5fKOXvhqHUZKFp5bAZFVGeh0d5KrHTo86ExoGxBQ37S/0I0obakIQpqje6A0EU3f+D9bGaNE9vStvQ/o8ENd1XtZ7x57AWRaU8guEjbys7QIxIydf+8kDvGFBEas8fq3W9T+VjpNIId/nmv90gyB8PirwCt/IpZuRw8G4EA6MzmYM1peqFOsttL6ozRrVlH4MVwxkDymdIdhNSZN6DJXQwxcZ7rmL1dh2EcEzJ+yURyKU6JqKIDxNygOY4PtX3JpAv2sLJqreaEg0m94yx6RTlV5HnqGXtdbAEd4go7MfsGrZRBJGFMClsUutWlRecPiZ5u9PwnV+ovo38gEnrkED5cljS9CqQSA+MKC7RADpSqJsBo6hfJUPw0JDenX+CepJArlUqwDujtUtKsvKy9aG2kTGy61imsJru+Crjvx3JUskf2dGctbJHndbNm69CVEbgkSC2W53PrSA1D6qcsyuEkPccxWLosjGKKx5rOsZXjdRaU5157FOzJVip0eWFCJdTxRM8Yh7WK6CNe5X/PfIfOtoSW6CPd57XiYdbr6QSKfQNHsQ+3uOGuSpy5Q6VzvEMl4dLiub8=
  - FILES: core.js
  - GH_REPO: github.com/wiris/moodle-atto_wiris.git
=======
    - secure: TEJUGFxovHar1xQ3w55pepK9mhTRrlV6TUcR/q47t6ALK5TUr7P0alRrqq58lhNt8gP5OfC4AlVvmuAYCTi7fS8iJ7dvmm7OYCthZdbybvoKibgJo2HIK4+8AjwHAyev/+w6/6lv5nXkU0VCDJknaxMeG2JSqUhmRpRn8RwqiG1rgiQh9CJUI6cIrSKoDbhuOywxoxbOvZYOKX6U9z7kqy+Ms+OJM3bjyRw8bSbRu2OpVXQBuBrrPCGP6UTabK6YhvUML0KH1cQ6VVhX/j6MpFFRD+5XR8NOKFdP6KM0rgRJ+ls7WADzXUQSvDPia5LhkXjZXAEMAXrjsjGPwXfivuiUZWl8bW0PjMqtcTTzy6G0b2AkceUk/WFbb7AtuinmoLzoWTa1H7xBIQwx/gVq+cUNM/sdP/JpRoALvEm9cn+2rgUFdEc/XXgJ/SRm8cLZRJ2U4xNsse6Uh3q+DBG+cefBzkhVJ4k1VAaroSry465z6sS+JwSp/K+Oubem9jW1lo3xvhsgYLVCD4boWw4aebVD02Rf9+qTNjq3V0HJDJ3sauclNO0zG+rREMzcrJyb9KnoEKkm+ET9SmQIHyRu4q+gaNSSnNHp275CGVSeoJDytdcXtuKiMFiid0p/EFmxQs9HgDVXJ4GfsBCHzMH3Lmk+SMnxblB1ReWLgJ7FyFg=
    - FILES: "core.js"
    - GH_REPO : "github.com/wiris/mathtype-integration-js-dev.git"
>>>>>>> PLUGINS-1188: Update .travis file
install:
- npm install
script:
- npm run lint
- export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
after_success:
- npm install
- npm run build
<<<<<<< HEAD
- git config --global user.email "travis@travis-ci.org"
- git config --global user.name "Travis CI"
- git clone https://github.com/wiris/moodle-atto_wiris.git
- cd moodle-atto_wiris
- git checkout -B $BRANCH
- mv -f ../${FILES} .
- git add ${FILES}
- sed -i "s/\$plugin->version = [[:digit:]]*/\$plugin->version = $(date +%Y%m%d00)/" version.php
- sed -i "s/MATURITY_STABLE/MATURITY_BETA/" version.php
- git add version.php
- git commit -m "JS API $(date +%Y%m%d) development version"
- echo "TRAVIS_BRANCH=$TRAVIS_BRANCH, PR=$PR, BRANCH=$BRANCH"
- git push https://${GH_TOKEN}@${GH_REPO} $BRANCH > /dev/null 2>&1
=======
- git clone https://github.com/wiris/mathtype-integration-js-dev.git
- mv -f ${FILES} mathtype-integration-js-dev
- cd mathtype-integration-js-dev
- git add ${FILES}
- git commit -m "Test"
- git push "https://${TRAVIS_SECURE_TOKEN_NAME}@${GH_REPO}" master > /dev/null 2>&1

>>>>>>> PLUGINS-1188: Update .travis file
